<?php
namespace frontend\widgets;
use yii\base\Widget;

class CategoryWidget extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run2()
    {

            $category_html = $this->renderFile('@app/widgets/view/catelist.php');
        return $category_html;
    }
    //redis 缓存
    public function run()
    {
        $redis=new \Redis();
        if($redis->open('127.0.0.1')){
            $category_html=$redis->get('category_html');
            if($category_html==''){
                $category_html = $this->renderFile('@app/widgets/view/catelist.php');
                $redis->set('category_html',$category_html);
                $category_html=$redis->get('category_html');
                return $category_html;
            }
            return $category_html;
        }else{
            $category_html = $this->renderFile('@app/widgets/view/catelist.php');
            return $category_html;
        }

    }
}