<?php
namespace frontend\widgets;
use yii\base\Widget;

class ListWidgets extends Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    //redis 缓存
    public function run()
    {
        $redis=new \Redis();
        if($redis->open('127.0.0.1')){
            $list_html=$redis->get('list_html');
            if($list_html==''){

                $list_html = $this->renderFile('@app/widgets/view/list.php');
                $redis->set('list_html',$list_html);
                $list_html=$redis->get('list_html');
                return $list_html;
            }
            return $list_html;
        }else{

            $list_html = $this->renderFile('@app/widgets/view/list.php');
            return $list_html;
        }

    }
}