<?php
namespace frontend\widgets;


use backend\models\GoodsSearch;
use yii\base\Widget;

class SearchWidgets extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $search=new GoodsSearch();
        $search_html = $this->renderFile('@app/widgets/view/search.php',['search'=>$search]);
        return $search_html;
    }

}